### ISSUE TITLE
Can I use this library?

### ISSUE THREAD

**Issue by ghost** [jruesga/timeline-chart-view#2]
Hi, Can I use this library in my application that I want to publish on
google play? Is there an obstacle to this? (I ask you in terms of licence)

**Comment by jruesga** [comment]
Yes, sure. I built it for that purpose ;). It is Apache 2 licensed so you can use freely (check license restrictions here https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))

**Comment by ghost** [comment]
thank you very much👍 I wanna ask one small question. When I use your sample codes, I see hours instead of dates like on youtube video. How can I change hours to dates?  
![ask](https://user-images.githubusercontent.com/30846080/30006836-9f362be8-910a-11e7-8c7f-7e9276250c05.png)
(I mean, 01:00, 02:00.... after 02 SEP) (It should be 03 SEP, 04 SEP)

**Comment by jruesga** [comment]
Then you should return a date with hour, minute, second and millisecond equals to 0. It your dataset contains intraday times, the library try to adjust the tick labels to display the proper time.

**Comment by jruesga** [comment]
If you have timestamps in a database you should aggregate your data into a day-truncated timestamp. You can do that with a query like:

```
select cast(strftime('%s', date(my_timestamp_field_name/1000,'unixepoch','localtime'), 'utc') AS INT)*1000 my_timestamp_field_name, sum(my_event_count_field_name) my_event_count_field_name
from mytable
where ....
) group by (cast(strftime('%s', date(my_timestamp_field_name/1000,'unixepoch','localtime'), 'utc') AS INT)*1000)
```
where my_timestamp_field_name is the field containing the timestamps events, and my_event_count_field_name the field to aggregate.

**Comment by ghost** [comment]
Firstly thanks, I just use your sample codes (https://github.com/jruesga/timeline-chart-view/tree/master/sample) I haven't done extra things **for now.** Can you share a link or codes because I am a beginner and I couldn't solve with these codes. (sorry)

**Comment by jruesga** [comment]
Sorry, but I developed the library with the intention to use it on [DataSharing](https://play.google.com/store/apps/details?id=com.awake.datasharing), which is a non-opensource app and I cannot share any code from it. If you have any specific question about how to do implement a thing, I could try to guide you with some snippet, but the sample app have almost all the needed code to deal with the library.

**Comment by ghost** [comment]
Actually, I was talking that I couldn't solve above problem and I wanted a link or codes about how can I change hours to date. Isn't there any way other than above answer?

**Comment by jruesga** [comment]
If you want only hours in the sample app, just change the HOUR_OF_DAY by DAY_OF_YEAR (here is the sample activity modified https://paste.ruesga.com/view/2e3c9005). This changes are unrelated to the library, but justto Java Calendar. As said before, if you want to show only dates (and not hour), you should truncated dates to the library.

**Comment by ghost** [comment]
Thanks for your effort, it works as I want. (I said that it is small question and I am beginner. I must work harder with java calendar)
