### ISSUE TITLE
How do I set the data for each date separately?

### ISSUE THREAD

**Issue by ghost** [jruesga/timeline-chart-view#3]
I want to set data into dates but they should be separate. For example, it should be like: serie1: 3, serie2: 6, serie3: 9 for SEPTEMBER 07 and serie1: 7, serie2: 8, serie3: 5 for SEPTEMBER 08. (I don't want random, I want to enter by manual) How can I do without fork? or should I do fork?

**Comment by jruesga** [comment]
You must return a cursor with 2 rows and with 4 columns each: the first column must be a long with the timestamp, and the following columns represent the values of each serie for that timestamp. You can obtain the cursor from a database or a content provider.
 
If you want to use the fixed data you described, you could use the InMemoryCursor class from the sample project (just copy it to your app) and use the following snippet of code:

```
TimelineChartView graph = findViewById(R.id.graph);
// Configure your graph...

final String[] COLUMN_NAMES = {"timestamp", "Serie1", "Serie2", "Serie3"};
InMemoryCursor cursor = new InMemoryCursor(COLUMN_NAMES);
List<Object[]> data = new ArrayList<>();
// Sept-7
Object[] item = new Object[COLUMN_NAMES.length];
item[0] = 1504735200000L;
item[1] = 3;
item[2] = 6;
item[3] = 9;
data.add(item);
// Sept-8
item = new Object[COLUMN_NAMES.length];
item[0] = 1504821600000L;
item[1] = 7;
item[2] = 8;
item[3] = 5;
data.add(item);
cursor.addAll(data);
graph.observeData(cursor);
```

**Comment by zurnacibatuhan** [comment]
You are great, thanks
