### ISSUE TITLE
How can I save two or more dates in same item[0]

### ISSUE THREAD

**Issue by ghost** [jruesga/timeline-chart-view#4]
Hi, I select dates in first activity and I send them to second activity which contains Object[] item.  However, I can see **only one date which I selected last** because they **change with each other in every time**. I need to see them side by side. They shouldn't change with each other.

Detailed information is here. Can you look this? 
https://stackoverflow.com/q/46214949/8604552

I think, the problem might be in item[0], so how can I save two or more dates in same item[0]?

**Comment by jruesga** [comment]
@LewisCornelius the library, and hence OnSelectedItemChangedListener, only reports a single selection (it doesn't allow multiple selections), so if you should store every selection you want to pass to another activity by your self.

You can do this by using a Preference and storing every selection or by passing a bundle between the activities. You can create yor own Parcelable (sorry i forgot to made Item parcelable) and serialize every selection.

**Comment by ghost** [comment]
Thanks for the answer but can you explain your answer step by step? For example, 
Firstly, If you mean sharedPreferences, I started to use it after sharing this question, so I did not add it. If you check again, I edited the question and added it. However, I don't understand how can I fix this with **sharedPreferences or Bundle.** (Even if I use sharedPreferences, it doesn't work as I want)
Secondly, Should I use parcelable for solving and **what should I do** with parceable?

**Comment by jruesga** [comment]
- Create a parcelable class with a long and array of doubles
- Override onCreate and onSavedInstance to save/restore a arraylist of that parcelable class
- Before start the activity b save create a new instance of the parcelable with the current selection and add the arraylist as an parcelable array extra in the intent
- Obtain the parcelable array extra from the intent
